# Generated by Django 3.2.5 on 2021-08-13 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FuturePlanning', '0021_mysettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='c_records',
            name='Start_Value',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='c_records',
            name='End_Date',
            field=models.CharField(default='10 2022', max_length=20),
        ),
        migrations.AlterField(
            model_name='c_records',
            name='Rec_Type',
            field=models.CharField(choices=[('1', 'In'), ('2', 'Exp'), ('3', 'Savings'), ('4', 'Loans')], default=('1', 'In'), max_length=7),
        ),
        migrations.AlterField(
            model_name='c_records',
            name='Start_Date',
            field=models.CharField(default='10 2021', max_length=20),
        ),
    ]
