# Generated by Django 3.2.5 on 2022-02-20 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FuturePlanning', '0022_auto_20210813_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='c_records',
            name='End_Date',
            field=models.CharField(default='07 2022', max_length=20),
        ),
        migrations.AlterField(
            model_name='c_records',
            name='Start_Date',
            field=models.CharField(default='07 2020', max_length=20),
        ),
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_site', models.URLField(blank=True)),
                ('profile_pic', models.ImageField(blank=True, upload_to='basic_app/profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
